SAVE_FREQ: 0

DATA:
  DATASET: SBVPI
  IMG_SIZE: 256
  BATCH_SIZE: 32
  MEAN_AND_STD_TYPE: vessels
  NORMALIZE: False

MODEL:
  NAME: TinyViT-256
  TYPE: tiny_vit
  NUM_CLASSES: 120

  DROP_PATH_RATE: 0.1

  TINY_VIT:
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 18 ]
    WINDOW_SIZES: [ 12, 12, 24, 12 ]
    EMBED_DIMS: [96, 192, 384, 576]

TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
  EVAL_BN_WHEN_TRAINING: True

TEST:
  CROP: False

AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
  HFLIP: 0.0
  AUTO_AUGMENT: none
  ROTATE: 15
  TRANSLATE: 0.1
  SCALE: 1.2
  SHEAR: 5
